### ISSUE TITLE
could you show your train loss?

### ISSUE THREAD

**Issue by RanFeng** [fabbrimatteo/VHA#1]
Yours work is impressive! could you show your train loss and epoch?

**Comment by fabbrimatteo** [comment]
Here you are. Training loss for the autoencoder with sigma 8 (gray), sigma 4 (orange) and sigma 2 (blue). Training was done sequentially.
![loss](https://user-images.githubusercontent.com/11458515/105345470-970fd380-5be4-11eb-9c79-62321e6c725f.jpg)
